#include "bcm2835.h"



gpio_t* GPIO = (gpio_t*)(PERIPHERAL_BASE + GPIO_OFFSET);
aux_t* AUX = (aux_t*)(PERIPHERAL_BASE + AUX_OFFSET);
sys_timer_t* SYS_TIMER = (sys_timer_t*)(PERIPHERAL_BASE + SYS_TIMER_OFFSET);
arm_timer_t* ARM_TIMER = (arm_timer_t*)(PERIPHERAL_BASE + ARM_TIMER_OFFSET);
irq_controller_t* IRQ_CONTROLLER = (irq_controller_t*)(PERIPHERAL_BASE + INTERRUPT_CONTROLLER_OFFSET);
uint32_t* RESET_CONTROLLER = (uint32_t*)(PERIPHERAL_BASE + PM_OFFSET + PM_RSTC_OFFSET);
uint32_t* WATCHDOG = (uint32_t*)(PERIPHERAL_BASE + PM_OFFSET + PM_WDOG_OFFSET);
emmc_t* EMMC = (emmc_t*)(PERIPHERAL_BASE + EMMC_OFFSET);

dma_channel_t* DMA_CHANNEL[DMA_CHANNEL_NUM] = {
  (dma_channel_t*) PERIPHERAL_BASE + DMA_CONTROLLER_OFFSET,
  (dma_channel_t*) PERIPHERAL_BASE + DMA_CONTROLLER_OFFSET + 0x100,
  (dma_channel_t*) PERIPHERAL_BASE + DMA_CONTROLLER_OFFSET + 0x200,
  (dma_channel_t*) PERIPHERAL_BASE + DMA_CONTROLLER_OFFSET + 0x300,
  (dma_channel_t*) PERIPHERAL_BASE + DMA_CONTROLLER_OFFSET + 0x400,
  (dma_channel_t*) PERIPHERAL_BASE + DMA_CONTROLLER_OFFSET + 0x500,
  (dma_channel_t*) PERIPHERAL_BASE + DMA_CONTROLLER_OFFSET + 0x600,
  (dma_channel_t*) PERIPHERAL_BASE + DMA_CONTROLLER_OFFSET + 0x700,
  (dma_channel_t*) PERIPHERAL_BASE + DMA_CONTROLLER_OFFSET + 0x800,
  (dma_channel_t*) PERIPHERAL_BASE + DMA_CONTROLLER_OFFSET + 0x900,
  (dma_channel_t*) PERIPHERAL_BASE + DMA_CONTROLLER_OFFSET + 0xa00,
  (dma_channel_t*) PERIPHERAL_BASE + DMA_CONTROLLER_OFFSET + 0xb00,
  (dma_channel_t*) PERIPHERAL_BASE + DMA_CONTROLLER_OFFSET + 0xc00,
  (dma_channel_t*) PERIPHERAL_BASE + DMA_CONTROLLER_OFFSET + 0xd00,
  (dma_channel_t*) PERIPHERAL_BASE + DMA_CONTROLLER_OFFSET + 0xe00,
  (dma_channel_t*) PERIPHERAL_BASE + DMA15_OFFSET
};

