# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: CMake Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # Set up a matrix to run the following configuration:
      #   <Linux, Release, latest GCC compiler toolchain on the default runner image, default generator>
      #
      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:
        os: [ubuntu-latest]
        build_type: [Release]
        c_compiler: [gcc]
        include:
          - os: ubuntu-latest
            c_compiler: gcc
            cpp_compiler: g++

    steps:
    - uses: actions/checkout@v4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        submodules: true

    - name: Environment
      run: |
        git submodule update --init --recursive
        git clone --depth 1 https://github.com/raspberrypi/firmware.git firmware
        docker pull 03predo/predos:v1.0
        docker run --rm -id -v $PWD/:/root/predOS --name predos 03predo/predos:v1.0

    - name: Build
      run: docker exec -i predos bash -c 'cd predOS ; make build'

    - name: Test
      run: |
        docker exec -i predos bash -c 'cd predOS ; make build_test'
        docker exec -i predos bash -c 'cd predOS ; make run_test'

